name: getsocket
description: A extra light package to websocket on Flutter on Android, iOS, Web, Windows, Mac and Linux
version: 1.0.2
homepage: https://github.com/jonataslaw/getsocket

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
